general_params:
  baud_rate: 3000000
  device_name: /dev/serial/by-id/usb-FTDI_USB__-__Serial_Converter_FT4NQ6SW-if00-port0
  pub_current: false
  pub_pos: true
  pub_vel: false
  joint_feedback_topic: /dom/end_eff/feedback_joint_states
  joint_command_topic: /dom/end_eff/command_joint_states
  dynamixel_type: "XC330-M288"
  start_pos_deg: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  min_position_deg: [0.0, -30.0, 0.0, 0.0, 0.0, -30.0, 0.0, 0.0, 0.0, -30.0, 0.0, 0.0, 0.0, -60.0, 0.0, 0.0]
  max_position_deg: [90.0, 30.0, 90.0, 90.0, 90.0, 30.0, 90.0, 90.0, 90.0, 30.0, 90.0, 90.0, 90.0, 60.0, 90.0, 90.0]
  return_delay_time: 100
  control_mode: "current_control" # Modes currently are "current_control" and "current_based_position_control"

current_based_position_control_params:
  kD: 100
  kI: 0
  kP: 600
  velocity_limit: 100
  profile_acceleration: 20
  profile_velocity: 100
  percent_current_limit: 100

current_control_params:
  kD: [0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05]
  kI: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  kP: [6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0]
  percent_current_limit: 100
