baud_rate: 3000000
device_name: /dev/serial/by-id/usb-FTDI_USB__-__Serial_Converter_FT8ISZ8G-if00-port0
kD: 100
kI: 0
kP: 400
percent_current_limit: 100
pub_current: false
pub_pos: true
pub_vel: false
start_pos_deg: [44.704, 3.784, 32.912, 21.384, 47.168, 4.4, 32.736, 14.432, 50.776, 3.52, 30.536, 18.216, 38.544, 1.056, 19.976, 17.776]
joint_feedback_topic: /dom/end_eff/feedback_joint_states
joint_command_topic: /dom/end_eff/command_joint_states
dynamixel_type: "XC330-M288"
